#!/usr/bin/env python3
"""
Logitech Device Spoofing Configuration

Provides device identity information to make virtual HID devices appear
as legitimate Logitech hardware to the Windows guest VM.
"""

import os
import struct
from dataclasses import dataclass
from typing import Optional


@dataclass
class DeviceIdentity:
    """Complete device identity for USB HID spoofing."""
    vendor_id: int
    product_id: int
    version: int
    name: str
    manufacturer: str
    serial: str
    physical_path: str


# Logitech Vendor ID (same for all Logitech devices)
LOGITECH_VENDOR_ID = 0x046d

# Device profiles that closely match real Logitech hardware
DEVICE_PROFILES = {
    'mouse_m510': DeviceIdentity(
        vendor_id=LOGITECH_VENDOR_ID,
        product_id=0xc52b,
        version=0x1200,  # Firmware version
        name='Logitech USB Receiver',
        manufacturer='Logitech',
        serial='0000000000000000',  # Unifying receivers often have this
        physical_path='/devices/pci0000:00/0000:00:14.0/usb1/1-1'
    ),
    'mouse_m705': DeviceIdentity(
        vendor_id=LOGITECH_VENDOR_ID,
        product_id=0x101b,
        version=0x2200,
        name='Logitech M705',
        manufacturer='Logitech',
        serial='0000000000000000',
        physical_path='/devices/pci0000:00/0000:00:14.0/usb1/1-2'
    ),
    'keyboard_k350': DeviceIdentity(
        vendor_id=LOGITECH_VENDOR_ID,
        product_id=0xc534,
        version=0x0900,
        name='Logitech USB Receiver',
        manufacturer='Logitech',
        serial='0000000000000000',
        physical_path='/devices/pci0000:00/0000:00:14.0/usb1/1-3'
    ),
    'keyboard_k400': DeviceIdentity(
        vendor_id=LOGITECH_VENDOR_ID,
        product_id=0x400e,
        version=0x0800,
        name='Logitech K400',
        manufacturer='Logitech',
        serial='0000000000000000',
        physical_path='/devices/pci0000:00/0000:00:14.0/usb1/1-4'
    ),
    'unifying_receiver': DeviceIdentity(
        vendor_id=LOGITECH_VENDOR_ID,
        product_id=0xc52b,
        version=0x1200,
        name='Logitech USB Receiver',
        manufacturer='Logitech',
        serial='0000000000000000',
        physical_path='/devices/pci0000:00/0000:00:14.0/usb1/1-1'
    ),
}

# Default mouse and keyboard profiles
DEFAULT_MOUSE_PROFILE = 'mouse_m510'
DEFAULT_KEYBOARD_PROFILE = 'keyboard_k350'


def get_device_profile(profile_name: str) -> DeviceIdentity:
    """Get a device profile by name."""
    if profile_name not in DEVICE_PROFILES:
        raise ValueError(f"Unknown profile: {profile_name}. "
                        f"Available: {list(DEVICE_PROFILES.keys())}")
    return DEVICE_PROFILES[profile_name]


def generate_realistic_serial() -> str:
    """
    Generate a realistic-looking serial number.
    Logitech Unifying receivers often report all zeros, but
    some devices have actual serials.
    """
    import random
    # 50% chance of all zeros (common for Unifying)
    if random.random() < 0.5:
        return '0000000000000000'
    # Otherwise generate a hex serial
    return ''.join(random.choices('0123456789ABCDEF', k=16))


def generate_udev_rules(mouse_profile: str = DEFAULT_MOUSE_PROFILE,
                        keyboard_profile: str = DEFAULT_KEYBOARD_PROFILE,
                        output_path: str = '/etc/udev/rules.d/99-virtual-logitech.rules') -> str:
    """
    Generate udev rules to give the virtual devices proper symlinks
    in /dev/input/by-id/ that look like real Logitech hardware.
    """
    mouse = get_device_profile(mouse_profile)
    keyboard = get_device_profile(keyboard_profile)

    rules = f'''# Virtual Logitech HID devices
# Generated by logitech_spoofing.py

# Virtual Mouse (appears as {mouse.name})
SUBSYSTEM=="input", ATTRS{{idVendor}}=="{mouse.vendor_id:04x}", ATTRS{{idProduct}}=="{mouse.product_id:04x}", \\
    ATTRS{{manufacturer}}=="{mouse.manufacturer}", \\
    SYMLINK+="input/by-id/usb-{mouse.manufacturer}_{mouse.name.replace(' ', '_')}-event-mouse", \\
    TAG+="uaccess"

# Virtual Keyboard (appears as {keyboard.name})
SUBSYSTEM=="input", ATTRS{{idVendor}}=="{keyboard.vendor_id:04x}", ATTRS{{idProduct}}=="{keyboard.product_id:04x}", \\
    ATTRS{{manufacturer}}=="{keyboard.manufacturer}", \\
    SYMLINK+="input/by-id/usb-{keyboard.manufacturer}_{keyboard.name.replace(' ', '_')}-event-kbd", \\
    TAG+="uaccess"
'''
    return rules


def write_udev_rules(mouse_profile: str = DEFAULT_MOUSE_PROFILE,
                     keyboard_profile: str = DEFAULT_KEYBOARD_PROFILE) -> str:
    """Write udev rules file. Returns the path."""
    rules_path = '/etc/udev/rules.d/99-virtual-logitech.rules'
    rules_content = generate_udev_rules(mouse_profile, keyboard_profile, rules_path)

    try:
        with open(rules_path, 'w') as f:
            f.write(rules_content)

        # Reload udev rules
        os.system('udevadm control --reload-rules')
        os.system('udevadm trigger')

        return rules_path
    except PermissionError:
        raise PermissionError(f"Cannot write to {rules_path}. Run as root.")


class DeviceSpoofingConfig:
    """Configuration manager for device spoofing."""

    def __init__(self,
                 mouse_profile: str = DEFAULT_MOUSE_PROFILE,
                 keyboard_profile: str = DEFAULT_KEYBOARD_PROFILE):
        self.mouse = get_device_profile(mouse_profile)
        self.keyboard = get_device_profile(keyboard_profile)

    def get_uhid_create_params(self, device_type: str) -> dict:
        """
        Get parameters for UHID device creation.

        Args:
            device_type: 'mouse' or 'keyboard'

        Returns:
            Dict with bus, vendor, product, version, name
        """
        device = self.mouse if device_type == 'mouse' else self.keyboard

        return {
            'bus': 0x03,  # BUS_USB
            'vendor': device.vendor_id,
            'product': device.product_id,
            'version': device.version,
            'name': device.name.encode('utf-8'),
        }

    def get_evdev_create_params(self, device_type: str) -> dict:
        """
        Get parameters for evdev/uinput device creation.

        Args:
            device_type: 'mouse' or 'keyboard'

        Returns:
            Dict with vendor, product, version, name
        """
        device = self.mouse if device_type == 'mouse' else self.keyboard

        return {
            'vendor': device.vendor_id,
            'product': device.product_id,
            'version': device.version,
            'name': device.name,
        }

    def get_qemu_usb_args(self) -> list[str]:
        """
        Get QEMU command line arguments for USB passthrough.

        Returns:
            List of QEMU arguments for adding these devices
        """
        return [
            f'-device usb-host,vendorid=0x{self.mouse.vendor_id:04x},'
            f'productid=0x{self.mouse.product_id:04x}',
            f'-device usb-host,vendorid=0x{self.keyboard.vendor_id:04x},'
            f'productid=0x{self.keyboard.product_id:04x}',
        ]

    def get_proxmox_conf_lines(self, vm_id: int) -> list[str]:
        """
        Get Proxmox VM configuration lines for USB passthrough.

        Args:
            vm_id: Proxmox VM ID

        Returns:
            List of configuration lines for /etc/pve/qemu-server/{vm_id}.conf
        """
        return [
            f'# Virtual Logitech HID devices',
            f'usb0: host={self.mouse.vendor_id:04x}:{self.mouse.product_id:04x},usb3=1',
            f'usb1: host={self.keyboard.vendor_id:04x}:{self.keyboard.product_id:04x},usb3=1',
        ]


# Convenience instance with default profiles
default_config = DeviceSpoofingConfig()
